### ISSUE TITLE
Make `subscribe` aware of set handlers

### ISSUE THREAD

**Issue by sebastianst** [perun-network/erdstall-ts-sdk#53] opened 2021-08-10 10:51 UTC
`subscribe` currently subscribes to both, receipts and balance proofs. It should only subscribe to what handlers are set for. For the time being, we don't require it to be smart enough to add subscriptions if any handler is set after a `subscribe` call. It is sufficient that, if a user adds a new handler, they have to call `subscribe` again. This should also be documented in the API.

**Comment by RmbRT** [comment] 2022-04-25 12:25
Duplicate of #142

**Closed by RmbRT** 2022-04-25 12:26 UTC
